name: Setup MELCloud Home

on:
  workflow_dispatch:
    inputs:
      email:
        description: 'Email MELCloud Home'
        required: true
      password:
        description: 'Contrasenya MELCloud Home'
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Login MELCloud Home
        env:
          MC_EMAIL: ${{ inputs.email }}
          MC_PASS: ${{ inputs.password }}
        run: node setup.js
